name: teresa-cli
version: '0.1'
summary: Open source tool to deploy apps to Kubernetes clusters
description: |
  Teresa is an extremely simple platform as a service that runs on top of 
  Kubernetes.
  It uses a client-server model, the client sends high level commands 
  (create application, deploy, etc.) to the server, which translates them 
  to the Kubernetes API.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18
parts:
  teresa:
    plugin: dump
    source: .
    override-pull: |
      curl -sSLO https://github.com/luizalabs/teresa/releases/download/v0.30.1/teresa-linux-amd64
      mv teresa-linux-amd64 teresa
      chmod +x teresa
    build-packages:
    - curl
apps:
  teresa:
    command: teresa
    plugs: [home, network-bind]
